### ISSUE TITLE
Non-Critical: Composition/Delegation to remove duplicate code between CarTransport and RepairShop

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#11]
You currently have some duplicated code in CarTransport and RepairShop which could be moved into a separate class and then use composition and delegation. 

You could e.g. create a class which has a list of cars and functionality for loading and unloading and then let CarTransport and RepairShop have an attribute of that type and then use delegation when loading/unloading.

**Comment by rilind404** [comment]
We have discussed this in our group. We will not be implementing this as we are pressed on time with lab 3 and written assignment.

Hopefully you understand this decision. 👍
