### ISSUE TITLE
lab1#Task5#

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#6]
> Any attempt to call on gas() or break() using arguments outside the parameter will simply not fall under any of the if-statements, and therefor not change the speed 
> 

This is correct. However, the function will still be executed without anything happening, this is bad since it leaves the caller without any explenation on why nothing happened. Throwing an IllegalArgumentException would be better, hence giving the caller feedback on their faulty method call.

**Comment by rilind404** [comment]
Fixed this. Giving an argument out of range will now throw IllegalArgumentException. 

We've also created tests for this with assertThrows which pass without issue.
