### ISSUE TITLE
CRITICAL: Possible to access platform raise/lower through getPlatform()

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#7]
It is currently possible to access the raise/lower method for platform by calling e.g. `scania.getPlatform().raise()`, this makes it possible to lower/raise the platform while the truck is moving.

**Comment by rilind404** [comment]
Edited `getPlatform()` accordingly. We return a clone of the platform instead of the actual platform so if scania.getPlatform().raise() is called on this, it will only edit the clone. No change on the real/actual platform in use.
```Java
    public IPlatform getPlatform() {
        return platform.clone();
    }
```

Added test which passes:
```Java
    @Test
    public void can_i_malicious_raise_ramp() {
        truck.getPlatform().raise();
        assertEquals(0.0, truck.getPlatformAngle(), 0.0);
    }
```
