### ISSUE TITLE
CRITICAL: Cartransporter loading should be possible while platform is down. 

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#8]
You're currently checking if the ramp is raised before loading a car onto the platform in CarTransport. All you have to do is remove the ! before `isRampDown()`

https://github.com/Chimbobedeh/TDA553-lab1/blob/d92148e56ba8e9260fe2958742b2367d2c3efbf2/CarTransporter.java#L25-L32

**Comment by Chimbobedeh** [comment]
This has now been changed.
