### ISSUE TITLE
CRITICAL: Car can be unloaded while CarTransporter' ramp is raised

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#9]
You are currently checking if the ramp is up before unloading a car from the platform. All you have to do is remove the ! before `isRampDown()`. 

https://github.com/Chimbobedeh/TDA553-lab1/blob/d92148e56ba8e9260fe2958742b2367d2c3efbf2/CarTransporter.java#L34-L46

**Comment by Chimbobedeh** [comment]
This has now been changed.
